import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ResponsiveDrawer from "../components/MiniDrawer";
import Box from "@mui/material/Box";
import { StoreProvider } from "../store/StoreProvider";
import { Toaster } from "../components/ui/sonner";
import { cookies } from "next/headers";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app", 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const next = cookies().getAll().filter((cookie) => cookie.name == "accessToken")
  const Token = next[0]?.value || ""

  const isAccessTokenPresent = !!Token;


  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-cover bg-center bg-repeat`}
        style={{ backgroundImage: `url('/firstbg.webp')` }}
      >
        <Box sx={{ display: "flex", flexDirection: "row" }}>
          <StoreProvider>
            {isAccessTokenPresent && <ResponsiveDrawer />}
            <Box component="main" sx={{ flexGrow: 1 }} className="pt-16">
              {children}
            </Box>
          </StoreProvider>
        </Box>
        <Toaster richColors className="" />
      </body>
    </html>
  );
}
