import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ResponsiveDrawer from "@/components/MiniDrawer";
import Box from "@mui/material/Box";
import { StoreProvider } from "@/store/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <Box sx={{ display: "flex", flexDirection: "row" }}>
          <StoreProvider>
            <ResponsiveDrawer />
            <Box
              component="main"
              sx={{ flexGrow: 1 }}
              className="pt-16 bg-gray-800"
            >
              {children}
            </Box>
          </StoreProvider>
        </Box>
      </body>
    </html>
  );
}
